/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface IiifGallery {
    'ignore': string;
    'manifest': string;
    'reset': () => Promise<void>;
  }
  interface IiifGalleryItem {
    'item': Manifesto.IManifestResource;
    'selected': boolean;
  }
}

declare global {


  interface HTMLIiifGalleryElement extends Components.IiifGallery, HTMLStencilElement {}
  var HTMLIiifGalleryElement: {
    prototype: HTMLIiifGalleryElement;
    new (): HTMLIiifGalleryElement;
  };

  interface HTMLIiifGalleryItemElement extends Components.IiifGalleryItem, HTMLStencilElement {}
  var HTMLIiifGalleryItemElement: {
    prototype: HTMLIiifGalleryItemElement;
    new (): HTMLIiifGalleryItemElement;
  };
  interface HTMLElementTagNameMap {
    'iiif-gallery': HTMLIiifGalleryElement;
    'iiif-gallery-item': HTMLIiifGalleryItemElement;
  }
}

declare namespace LocalJSX {
  interface IiifGallery extends JSXBase.HTMLAttributes<HTMLIiifGalleryElement> {
    'ignore'?: string;
    'manifest'?: string;
    'onSelectCanvas'?: (event: CustomEvent<any>) => void;
    'onSelectCollection'?: (event: CustomEvent<any>) => void;
    'onSelectManifest'?: (event: CustomEvent<any>) => void;
  }
  interface IiifGalleryItem extends JSXBase.HTMLAttributes<HTMLIiifGalleryItemElement> {
    'item'?: Manifesto.IManifestResource;
    'onSelectItem'?: (event: CustomEvent<any>) => void;
    'selected'?: boolean;
  }

  interface IntrinsicElements {
    'iiif-gallery': IiifGallery;
    'iiif-gallery-item': IiifGalleryItem;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


