/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  MyComponent as IiifGallery
} from './components/iiif-gallery/iiif-gallery';

declare global {
  interface HTMLIiifGalleryElement extends IiifGallery, HTMLElement {
  }
  var HTMLIiifGalleryElement: {
    prototype: HTMLIiifGalleryElement;
    new (): HTMLIiifGalleryElement;
  };
  interface HTMLElementTagNameMap {
    "iiif-gallery": HTMLIiifGalleryElement;
  }
  interface ElementTagNameMap {
    "iiif-gallery": HTMLIiifGalleryElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "iiif-gallery": JSXElements.IiifGalleryAttributes;
    }
  }
  namespace JSXElements {
    export interface IiifGalleryAttributes extends HTMLAttributes {
      
        first?: string,
        last?: string
    }
  }
}

